const faceList = [
	{
		id:0,faceArr:[
			{code:'1f601',native:'😁',title:'笑脸'},
			{code:'1f602',native:'😂',title:'哭笑'},
			{code:'1f603',native:'😃',title:'开嘴'},
			{code:'1f604',native:'😄',title:'眯眼'},
			{code:'1f605',native:'😅',title:'冷汗'},
			{code:'1f606',native:'😆',title:'闭眼睛'},
			{code:'1f609',native:'😉',title:'眨眼'},
			{code:'1f60a',native:'😊',title:'脸红'},
			{code:'1f60b',native:'😋',title:'俏皮'},
			{code:'1f60c',native:'😌',title:'释放'},
			{code:'1f60d',native:'😍',title:'色'},
			{code:'1f60f',native:'😏',title:'阴险'}
		]
	},
	{
		id:1,faceArr:[
			{code:'1f612',native:'😒',title:'无趣'},
			{code:'1f613',native:'😓',title:'冷汗'},
			{code:'1f614',native:'😔',title:'沉思'},
			{code:'1f616',native:'😖',title:'苦涩'},
			{code:'1f618',native:'😘',title:'亲'},
			{code:'1f61a',native:'😚',title:'闭眼亲'},
			{code:'1f61c',native:'😜',title:'吐舌'},
			{code:'1f61d',native:'😝',title:'闭眼吐舌'},
			{code:'1f61e',native:'😞',title:'难过'},
			{code:'1f621',native:'😡',title:'愤怒'},
			{code:'1f622',native:'😢',title:'哭泣'},
			{code:'1f623',native:'😣',title:'坚持不懈'}
		]
	},
	{
		id:2,faceArr:[
			{code:'1f624',native:'😤',title:'出气'},
			{code:'1f625',native:'😥',title:'失意'},
			{code:'1f628',native:'😨',title:'恐惧'},
			{code:'1f629',native:'😩',title:'疲倦'},
			{code:'1f62a',native:'😪',title:'睡脸'},
			{code:'1f62d',native:'😭',title:'哭泣'},
			{code:'1f630',native:'😰',title:'冷汗'},
			{code:'1f631',native:'😱',title:'惊恐'},
			{code:'1f632',native:'😲',title:'惊讶'},
			{code:'1f633',native:'😳',title:'发呆'},
			{code:'1f635',native:'😵',title:'头晕'},
			{code:'1f637',native:'😷',title:'生病'}
		]
	},
	{
		id:3,faceArr:[
			{code:'1f47f',native:'👿',title:'恶魔'},
			{code:'1f60e',native:'😎',title:'酷'},
			{code:'1f446',native:'👆',title:'上'},
			{code:'1f447',native:'👇',title:'下'},
			{code:'1f448',native:'👈',title:'左'},
			{code:'1f449',native:'👉',title:'右'},
			{code:'1f44a',native:'👊',title:'拳头'},
			{code:'1f44b',native:'👋',title:'挥手'},
			{code:'1f44c',native:'👌',title:'ok'},
			{code:'1f44d',native:'👍',title:'强'},
			{code:'1f44e',native:'👎',title:'弱'},
			{code:'1f44f',native:'👏',title:'拍手'}
		]
	},
	{
		id:4,faceArr:[
			{code:'1f440',native:'👀',title:'眼睛'},
			{code:'1f489',native:'💉',title:'注射器'},
			{code:'1f48a',native:'💊',title:'胶囊'},
			{code:'1f48b',native:'💋',title:'唇'},
			{code:'1f48c',native:'💌',title:'爱情信'},
			{code:'1f48e',native:'💎',title:'宝石'},
			{code:'1f47b',native:'👻',title:'鬼'},
			{code:'1f460',native:'👠',title:'高跟鞋'},
			{code:'1f453',native:'👓',title:'眼镜'},
			{code:'1f437',native:'🐷',title:'猪'},
			{code:'1f434',native:'🐴',title:'马'},
			{code:'1f42f',native:'🐯',title:'老虎'}
		]
	},
	{
		id:5,faceArr:[
			{code:'1f3e5',native:'🏥',title:'医院'},
			{code:'1f3e6',native:'🏦',title:'银行'},
			{code:'1f3ec',native:'🏬',title:'百货'},
			{code:'1f3b5',native:'🎵',title:'音乐'},
			{code:'1f3b8',native:'🎸',title:'吉他'},
			{code:'1f3c0',native:'🏀',title:'球'},
			{code:'1f3a8',native:'🎨',title:'绘画'},
			{code:'1f3a5',native:'🎥',title:'电影'},
			{code:'1f3a4',native:'🎤',title:'唱歌'},
			{code:'1f383',native:'🎃',title:'万圣节'},
			{code:'1f382',native:'🎂',title:'生日'},
			{code:'1f381',native:'🎁',title:'礼物'}
		]
	},
	{
		id:6,faceArr:[
			{code:'26a1',native:'⚡',title:'闪电'},
			{code:'26a0',native:'⚠',title:'警告'},
			{code:'260e',native:'☎',title:'电话'},
			{code:'2600',native:'☀',title:'太阳'},
			{code:'23f0',native:'⏰',title:'闹钟'},
			{code:'1f6b9',native:'🚹',title:'男士'},
			{code:'1f6ba',native:'🚺',title:'女士'},
			{code:'1f697',native:'🚗',title:'汽车'},
			{code:'1f680',native:'🚀',title:'火箭'},
			{code:'1f684',native:'🚄',title:'火车'},
			{code:'2708',native:'✈',title:'飞机'},
			{code:'1f6a4',native:'🚤',title:'船'}
		]
	}
	
]

export default faceList;